vich_uploader:
    db_driver: orm

    mappings:
        screens:
            uri_prefix: /images/screens
            upload_destination: '%kernel.project_dir%/public/images/screens'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
